### PR TITLE
added timesync prereq

### PR DESCRIPTION
**Pull request by sebbrandt87**
https://jira.mesosphere.com/browse/DCOS-56622

### CODE REVIEW

**Review by fatz — CHANGES_REQUESTED** [review]
i think there should be a fallback if chrony or ntpd are not installed.

What about having a variable `cloud_time_sync_package` and `time_sync_package` and guarding with a check if this system is running on a cloud machine / VM? 

So users could still overwrite the defaults but we always make sure timesync is installed and has happened

**Comment by sebbrandt87** [comment]
sure, lets talk about that in detail tomorrow :)

**Review by fatz — DISMISSED** [review]
lgtm

**Review by fatz — DISMISSED** [review]
lsgtm

**Review by fatz — DISMISSED** [review]

**Comment by sebbrandt87** [comment]
approved before by @fatz, just fixed the CI

**Pull request merged**
