### PR TITLE
detect the network interface to be used for win_dns_client task

### PR DESCRIPTION
**Pull request by sebbrandt87**

### CODE REVIEW

**Comment by sebbrandt87** [comment]
fyi: @sergiimatus

**Comment by fatz** [comment]
what is the purpose of this? Shouldn't this be covered by ipdetect?

**Comment by sergiimatusEPAM** [comment]
> what is the purpose of this? 
It's to workaround a bug when "win_dns_client" finds wrong interface to be setup with DNS. Sebastian suggested to filter out an interface which has no "default_gateway" setup
 
>Shouldn't this be covered by ipdetect?
"ipdetect" realized with presumption that the local DNS has been setup already. If you look here - https://docs.d2iq.com/mesosphere/dcos/1.13/installing/production/deploying-dcos/installation/#use-the-network-route-to-the-mesos-master, "master.mesos" var is already defined. 
In Windows implementation we used same way for ip_detect - having master.mesos presetup
 See example used in dcos-diagnostic:
https://github.com/OleksandrBielov/dcos-diagnostics/blob/master/files/detect_ip.ps1

**Comment by fatz** [comment]
@sergiimatusEPAM after speaking to @sebbrandt87 I now understand that this is part of workarounding dcos-dns

AFAIK we already talked about this topic a while ago. I really want to say how concerning this topic is to me.

Not only making masters a DNS bottleneck, but also adding the issue in multi region / multi cloud setups that those agents will get DNS responses meant for another host.

To give an example. Some AWS services are working with a split horizon view  so inside of AWS you get a private IP outside of AWS you get a public address. 

Consider you masters are deployed in AWS but your agent in a data center. Your application running on this agent will now get a private IP but might not be able to reach it.


I know that a central dcos.config introduces the same issue but also you're able to locally change the resolvers. Furthermore the current workaround is a list of resolvers and dcos-dns failes through.


I'll still be ok to merge this into the windows feature branch but also have to raise that this is extremly dangoures to ignore and could lead to weird problems for customers.

**Review by fatz — APPROVED** [review]
don't agree but problem already existed before this PR

**Pull request merged**
