### PR TITLE
Add the docker-ce repo to default jinja2 filter

### PR DESCRIPTION
**Pull request by rubioks**
This task seems to fail in case of non RHEL system, due to enablerepo parameter can not be empty string. We have tested this change in several Centos 7.6 system and ansible 2.7.0, inside our private cloud.

### CODE REVIEW

**Comment by sebbrandt87** [comment]
we cannot reproduce this as
https://github.com/dcos/dcos-ansible/blob/75ebc706794db582bfe4cb1fb95dd7ad669a396d/roles/DCOS.requirements/tasks/main.yml#L34-L42
enables the repo per default, so we would not add the enable repo param, but set it to an empty string.

Our CI runs against CentOS and RHEL.

Maybe the behaviour of enablerepo can be an empty string, was fixed in a bugfix/hotfix version of ansible 2.7.0. Would need to look this up.

**Comment by rubioks** [comment]
Hi sebbrandt87,

Thank you for your quick response . We just checked that in ansible 2.8.2 and CentOS 7.6 ,it´s possible to leave a empty string in 'enablerepo' parameter, which would effectively use the default repo. But in ansible 2.7.0 , this behaviour doesn´t seem to work . I'd really appreciate it if you could check it out.

Regards!

**Comment by sebbrandt87** [comment]
I would like to check it today if I find the time.

**Comment by sebbrandt87** [comment]
hey @rubioks,
please check once instead of `default('docker-ce')` the `default(omit)` filter :)
just used it somewhere else and this would fit what we try to do here :)
cheers

**Review by sebbrandt87 — CHANGES_REQUESTED** [review]
see https://github.com/dcos/dcos-ansible/pull/53#issuecomment-527348487

**Comment by rubioks** [comment]
Hi @sebbrandt87 !

We have checked the default(omit) filter and its works in our environment (Ansible 2.7 and Centos 7.6 VMs) :) . I think that its a good solution to enable the repo per default in Ansible < 2.8. 

Thank you so much !

**Comment by sebbrandt87** [comment]
okay, so if you would like to contribute the `default(omit)` filter in this PR, please make it so :)

**Comment by rubioks** [comment]
I will a new PR with this ,since I´ve reestructured my previous repo,  if that´s ok ;)

**Pull request closed without merging**
